---
apiVersion: v1
kind: Service
metadata:
  name: galega-ms-customer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "galega-ms-customer-lb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Load Balancer Interno
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"       # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # (Opcional) Especifica que o LB é interno
  labels:
    name: galega-ms-customer
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 7777        # Porta que será exposta
      targetPort: 7777  # Porta no container que receberá o tráfego
  selector:
    app: galega-ms-customer # Label selector para encontrar os pods corretos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galega-ms-customer
spec:
  selector:
    matchLabels:
      app: galega-ms-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: galega-ms-customer
    spec:
      containers:
        - name: galega-ms-customer
          image: 775370709632.dkr.ecr.us-east-1.amazonaws.com/galega-ms-customer-app:latest
          ports:
            - containerPort: 7777

          # Setting Enviornmental Variables
          envFrom:
            - configMapRef:
                name: galega-ms-customer-config